[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "omnifocus-mcp"
version = "0.2.0"
description = "MCP server for OmniFocus integration"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.12.0",
]

[project.scripts]
omnifocus-mcp = "omnifocus_mcp.server_fastmcp:mcp.run"
