name: Mistake Tracking Validation

on:
  pull_request:
    branches: [ main, feature/* ]
  push:
    branches: [ main, feature/* ]

jobs:
  validate-prevention-measures:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest radon

      - name: Check version synchronization
        run: |
          chmod +x scripts/check_version_sync.sh
          ./scripts/check_version_sync.sh

      - name: Summary
        if: success()
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "✅ Hygiene checks passed!"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "Checks validated:"
          echo "  ✅ Version synchronization"
          echo ""
          echo "Note: Mistake tracking checks moved to Claude Code hooks"
          echo "This PR is safe to merge from a hygiene perspective."
