name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-asyncio pytest-cov radon

      - name: Run unit tests (excluding integration tests)
        run: pytest tests/ -m "not integration"
        timeout-minutes: 5

      - name: Check code complexity
        run: ./scripts/check_complexity.sh
        continue-on-error: true

      - name: Verify client/server parity
        run: ./scripts/check_client_server_parity.sh

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [unit-tests]
    if: always()

    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.unit-tests.result }}" != "success" ]; then
            echo "Unit tests failed"
            exit 1
          fi
          echo "All required tests passed"
